import React, { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';
import './Reports.css';

const Reports = () => {
  const { user } = useAuth();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedReport, setSelectedReport] = useState(null);

  const fetchReports = useCallback(async () => {
    try {
      setLoading(true);
      const response = await api.get('/reports/my-reports');
      setReports(response.data || []);
    } catch (err) {
      console.error('Error fetching reports:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchReports(); }, [fetchReports]);

  const generateNewReport = async () => {
    setGenerating(true);
    try {
      const response = await api.post('/reports/financial-summary');
      setReports([response.data, ...reports]);
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to generate report. Make sure you have goals set up first.');
    } finally {
      setGenerating(false);
    }
  };

  const deleteReport = async (reportId) => {
    if (!window.confirm('Are you sure you want to delete this report?')) return;
    try {
      await api.delete(`/reports/${reportId}`);
      setReports(reports.filter(r => r._id !== reportId));
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to delete report');
    }
  };

  const getReportIcon = (type) => {
    const icons = { financial_summary: '📊', goal_progress: '🎯', contribution_analysis: '💰', wealth_growth: '📈' };
    return icons[type] || '📄';
  };

  if (loading) {
    return <div className="reports-page"><div className="reports-container"><div className="loading">Loading reports...</div></div></div>;
  }

  return (
    <div className="reports-page">
      <div className="reports-container">
      <div className="reports-header">
        <div>
          <h2>📊 Financial Reports</h2>
          <p style={{color:'#64748b',margin:'4px 0 0',fontSize:'0.95rem'}}>Generate and review your family's financial summaries</p>
        </div>
        <button className="fm-btn fm-btn-primary" onClick={generateNewReport} disabled={generating}>
          {generating ? '⏳ Generating...' : '📈 Generate Report'}
        </button>
      </div>

      {reports.length === 0 ? (
        <div className="fm-empty">
          <div className="fm-empty-icon">📊</div>
          <h3>No Reports Yet</h3>
          <p>Generate your first financial report to track your family's progress!</p>
          <button className="fm-btn fm-btn-primary" onClick={generateNewReport} disabled={generating}>
            {generating ? 'Generating...' : 'Generate First Report'}
          </button>
        </div>
      ) : (
        <div className="reports-grid">
          {reports.map((report) => (
            <div key={report._id} className="report-card">
              <div className="report-header">
                <div className="report-icon">{getReportIcon(report.type)}</div>
                <div className="report-info">
                  <h3>{report.title}</h3>
                  <p className="report-type">{(report.type || '').replace(/_/g, ' ')}</p>
                  <p className="report-date">
                    {new Date(report.createdAt).toLocaleDateString('en-IN')} •
                    Generated by {report.generatedBy?.name || user?.name || 'You'}
                  </p>
                </div>
                <div className="report-actions">
                  <button className="fm-btn fm-btn-primary" style={{padding:'6px 14px',fontSize:'0.8rem'}} onClick={() => setSelectedReport(report)}>View</button>
                  <button className="fm-remove-btn" style={{position:'static',opacity:1,width:28,height:28,fontSize:'0.9rem'}} onClick={() => deleteReport(report._id)}>×</button>
                </div>
              </div>

              <div className="report-preview">
                {report.type === 'financial_summary' && report.data?.goals && (
                  <div className="preview-content">
                    <div className="preview-stats">
                      <div className="stat">
                        <span>Total Goals</span>
                        <strong>{report.data.goals.total || 0}</strong>
                      </div>
                      <div className="stat">
                        <span>Progress</span>
                        <strong>{(report.data.goals.overallProgress || 0).toFixed(1)}%</strong>
                      </div>
                      <div className="stat">
                        <span>Contributions</span>
                        <strong>₹{(report.data.contributions?.total || 0).toLocaleString()}</strong>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Report Detail Modal */}
      {selectedReport && (
        <div className="fm-modal-overlay" onClick={() => setSelectedReport(null)}>
          <div className="fm-modal" style={{maxWidth:700}} onClick={(e) => e.stopPropagation()}>
            <div className="fm-modal-header">
              <h3>{selectedReport.title}</h3>
              <button className="fm-close-btn" onClick={() => setSelectedReport(null)}>×</button>
            </div>

            <div style={{padding:'20px 28px'}}>
              <div className="detail-section">
                <h4 style={{marginBottom:12}}>📋 Report Overview</h4>
                <div className="fm-detail-row" style={{display:'flex',justifyContent:'space-between',padding:'10px 14px',background:'#f8fafc',borderRadius:10,marginBottom:8}}>
                  <span style={{color:'#64748b',fontSize:'0.85rem'}}>Type</span>
                  <strong style={{fontSize:'0.9rem',color:'#1e293b'}}>{(selectedReport.type || '').replace(/_/g, ' ')}</strong>
                </div>
                <div className="fm-detail-row" style={{display:'flex',justifyContent:'space-between',padding:'10px 14px',background:'#f8fafc',borderRadius:10,marginBottom:8}}>
                  <span style={{color:'#64748b',fontSize:'0.85rem'}}>Period</span>
                  <strong style={{fontSize:'0.9rem',color:'#1e293b'}}>
                    {selectedReport.period?.startDate ? new Date(selectedReport.period.startDate).toLocaleDateString('en-IN') : 'N/A'} -
                    {selectedReport.period?.endDate ? new Date(selectedReport.period.endDate).toLocaleDateString('en-IN') : 'N/A'}
                  </strong>
                </div>
              </div>

              {selectedReport.data?.family && (
                <div className="detail-section" style={{marginTop:20}}>
                  <h4 style={{marginBottom:12}}>👨‍👩‍👧‍👦 Family Summary</h4>
                  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:12}}>
                    <div style={{padding:14,background:'#f0fdf4',borderRadius:12,textAlign:'center'}}>
                      <div style={{fontSize:'0.75rem',color:'#64748b',marginBottom:4}}>Total Wealth</div>
                      <strong style={{color:'#16a34a'}}>₹{(selectedReport.data.family.totalWealth || 0).toLocaleString()}</strong>
                    </div>
                    <div style={{padding:14,background:'#eff6ff',borderRadius:12,textAlign:'center'}}>
                      <div style={{fontSize:'0.75rem',color:'#64748b',marginBottom:4}}>Monthly Income</div>
                      <strong style={{color:'#3b82f6'}}>₹{(selectedReport.data.family.monthlyIncome || 0).toLocaleString()}</strong>
                    </div>
                    <div style={{padding:14,background:'#fef3c7',borderRadius:12,textAlign:'center'}}>
                      <div style={{fontSize:'0.75rem',color:'#64748b',marginBottom:4}}>Members</div>
                      <strong style={{color:'#f59e0b'}}>{selectedReport.data.family.memberCount || 0}</strong>
                    </div>
                  </div>
                </div>
              )}

              {selectedReport.data?.goalsBreakdown && selectedReport.data.goalsBreakdown.length > 0 && (
                <div className="detail-section" style={{marginTop:20}}>
                  <h4 style={{marginBottom:12}}>🎯 Goals Progress</h4>
                  {selectedReport.data.goalsBreakdown.map((goal, index) => (
                    <div key={index} style={{marginBottom:12,padding:12,background:'#f8fafc',borderRadius:10}}>
                      <div style={{display:'flex',justifyContent:'space-between',marginBottom:6}}>
                        <span style={{fontWeight:600,color:'#1e293b',fontSize:'0.9rem'}}>{goal.name}</span>
                        <span style={{color:'#6366f1',fontWeight:600,fontSize:'0.85rem'}}>{(goal.progress || 0).toFixed(1)}%</span>
                      </div>
                      <div style={{height:6,background:'#e2e8f0',borderRadius:3,overflow:'hidden'}}>
                        <div style={{height:'100%',width:`${Math.min(100, goal.progress || 0)}%`,background:'#6366f1',borderRadius:3,transition:'width 0.5s ease'}}></div>
                      </div>
                      <div style={{display:'flex',justifyContent:'space-between',marginTop:4,fontSize:'0.78rem',color:'#64748b'}}>
                        <span>₹{(goal.current || 0).toLocaleString()}</span>
                        <span>₹{(goal.target || 0).toLocaleString()}</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {selectedReport.data?.contributions?.byMember && Object.keys(selectedReport.data.contributions.byMember).length > 0 && (
                <div className="detail-section" style={{marginTop:20}}>
                  <h4 style={{marginBottom:12}}>💰 Member Contributions</h4>
                  {Object.entries(selectedReport.data.contributions.byMember).map(([member, amount]) => (
                    <div key={member} style={{display:'flex',justifyContent:'space-between',padding:'10px 14px',background:'#f8fafc',borderRadius:10,marginBottom:6}}>
                      <span style={{fontWeight:500,color:'#1e293b'}}>{member}</span>
                      <span style={{fontWeight:700,color:'#10b981'}}>₹{amount.toLocaleString()}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="fm-modal-actions">
              <button className="fm-btn fm-btn-ghost" onClick={() => window.print()}>🖨️ Print</button>
              <button className="fm-btn fm-btn-primary" onClick={() => setSelectedReport(null)}>Close</button>
            </div>
          </div>
        </div>
      )}
      </div>
    </div>
  );
};

export default Reports;